name: Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    name: LinuxBuild
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: sudo apt-get install g++-10 gcc-10 libx11-dev xorg-dev freeglut3-dev libudev-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        CC: gcc-10
        CXX: g++-10

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      env:
        CC: gcc-10
        CXX: g++-10
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: Snake-linux
        path: ${{github.workspace}}/build/Snake
        