name: macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build-macos:
    name: macOSBuild
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        name: Snake-macOS
        path: ${{github.workspace}}/build/Snake
        